### ISSUE TITLE
No module named 'icu' 

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/normalize_text_to_df#5]
This is an issue on polyglot's end. To fix it please see:
https://github.com/aboSamoor/polyglot/issues/152#issuecomment-489266218

**Comment by LudvigOlsen** [comment]
On Mac OSX 12.6, this seems to work:

`conda install -c conda-forge pyicu morfessor icu -y && pip install pycld2 polyglot`

Found here: https://github.com/aboSamoor/polyglot/issues/80#issuecomment-417863726

**Comment by KennethEnevoldsen** [comment]
As this is an issue with polyglot it won't be addressed but the issue will remain open for anyone to see.

**Comment by KennethEnevoldsen** [comment]
I have now added the polyglot dependencies. So this shouldn't be an issue going forward.
