### ISSUE TITLE
'tokens' referenced before assignment

### ISSUE THREAD

**Issue by LudvigOlsen** [centre-for-humanities-computing/normalize_text_to_df#6]
I get `UnboundLocalError: local variable 'tokens' referenced before assignment` 
in `__get_sent_dict()` line 68 in text_to_sentiment.py.

It seems that `tokens` in df = self.__dict_model[l](text, tokens) is not assigned when tokenlist is `None`.

**Comment by LudvigOlsen** [comment]
I was passing a list of data frames instead of the TextToDf object. 
Probably still a bug though :)

Added the following to the texts_to_sentiment() method on my branch:

```
if isinstance(texts, list) and not isinstance(texts[0], str):
    # One may accidentally pass the list of preprocessed data frames
    raise ValueError(f"When 'texts' is a list, it must contain strings only.")
```

**Comment by KennethEnevoldsen** [comment]
text to sentiment should not be able to take a dataframe as it also uses the whole text for emoji detection

**Comment by KennethEnevoldsen** [comment]
@LudvigOlsen have this been added to the main branch or should I add it?

**Comment by LudvigOlsen** [comment]
It was merged in. I have nothing new on the dev branch currently. Not sure if the bug is completely solved though.

**Comment by KennethEnevoldsen** [comment]
this have been checked and solved
